# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproblem.proto\x12\x07problem\"\x1b\n\x0bTypeMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\")\n\x0cImageMessage\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03img\x18\x02 \x01(\t2I\n\x07Problem\x12>\n\x0fGenerateProblem\x12\x14.problem.TypeMessage\x1a\x15.problem.ImageMessageB\nZ\x08/problemb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'problem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010/problem'
  _TYPEMESSAGE._serialized_start=26
  _TYPEMESSAGE._serialized_end=53
  _IMAGEMESSAGE._serialized_start=55
  _IMAGEMESSAGE._serialized_end=96
  _PROBLEM._serialized_start=98
  _PROBLEM._serialized_end=171
# @@protoc_insertion_point(module_scope)
