# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import problem_pb2 as problem__pb2


class ProblemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateProblem = channel.unary_unary(
                '/problem.Problem/GenerateProblem',
                request_serializer=problem__pb2.TypeMessage.SerializeToString,
                response_deserializer=problem__pb2.ImageMessage.FromString,
                )


class ProblemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateProblem(self, request, context):
        """unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProblemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateProblem': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateProblem,
                    request_deserializer=problem__pb2.TypeMessage.FromString,
                    response_serializer=problem__pb2.ImageMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'problem.Problem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Problem(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateProblem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/problem.Problem/GenerateProblem',
            problem__pb2.TypeMessage.SerializeToString,
            problem__pb2.ImageMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
