# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analytics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"\x1c\n\x0cGradeRequest\x12\x0c\n\x04html\x18\x01 \x01(\t\"\x1c\n\rGradeResponse\x12\x0b\n\x03\x61\x63\x63\x18\x01 \x01(\t2N\n\x08\x41nlytics\x12\x42\n\rGradeAccuracy\x12\x17.analytics.GradeRequest\x1a\x18.analytics.GradeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GRADEREQUEST._serialized_start=30
  _GRADEREQUEST._serialized_end=58
  _GRADERESPONSE._serialized_start=60
  _GRADERESPONSE._serialized_end=88
  _ANLYTICS._serialized_start=90
  _ANLYTICS._serialized_end=168
# @@protoc_insertion_point(module_scope)
